version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input
install:
  - ps: Install-Product node 8 x64
  - git reset --hard HEAD
  - npm install
  - node --version
  - copy src/renderer/config.example.js src/renderer/config.js

build_script:
  - npm run build

artifacts:
  - path: build\*.exe
  - name: Release

deploy:
  - provider: GitHub
  - description: とりあえずインストーラー
  - auth_token: ${GITHUB_TOKEN}
  - artifact: Release
  - force_update: true

test: off
